[package]
name = "hacker-mod"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
dialog = "0.3.0"
notify-rust = "4"